version: "3"

networks:
  net_def:
    external: true
    
services:
  squid:
    image: ubuntu/squid:latest
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1G"
    volumes:
      - data:/etc/squid/squid.conf
    networks:
      - net_def
      
volumes:
  data:
    name: ubuntu_squid_data