version: "3"

# https://raw.githubusercontent.com/grafana/loki/v2.9.4/production/docker-compose.yaml

networks:
  net_def:
    external: true
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: 0 # IP 伪装, 为 0 无法访问容器网络之外的网络

services:
  loki:
    image: grafana/loki:2.9.4
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1G"
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - net_def

  promtail:
    image: grafana/promtail:2.9.4
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1G"
    depends_on:
      - loki
    volumes:
      - grafana_promtail_log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - net_def
  grafana:
    image: grafana/grafana-enterprise:latest
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1G"
    networks:
      - net_def
    # ports:
    #  - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
volumes:
  grafana_promtail_log:
    name: grafana_promtail_log
  grafana_data:
    name: grafana_data