version: '3.7'

networks:
  net_def:
    external: true
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: 0 # IP 伪装, 为 0 无法访问容器网络之外的网络

services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1G"
    user: root
    networks:
      - net_def
    # ports:
    #   - 8080:8080
    #   - 50000:50000
    volumes:
      - home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker

volumes:
  home:
    name: jenkins_home