version: "3"

networks:
  net_def:
    external: true
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: 0 # IP 伪装, 为 0 无法访问容器网络之外的网络

services:
  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    networks:
      - net_def
    ports:
      # - 8000:8000
      # - 9000:9000
      # - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data

volumes:
  data:
    name: portainer_data