version: '3'

networks:
  net_def:
    external: true
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: 0 # IP 伪装, 为 0 无法访问容器网络之外的网络

services:
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=${LOOKUPD_TCP_ADDRESS}
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1G"
    depends_on:
      - nsqlookupd
    # ports:
    #   - 4150:4150
    #   - 4151:4151
    networks:
      - net_def
    volumes:
      - data:/data
      - certs:/etc/ssl/certs

volumes:
  data:
    name: nsqd_data
  certs:
    name: nsqd_certs