version: '3'

networks:
  net_def:
    external: true
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: 0 # IP 伪装, 为 0 无法访问容器网络之外的网络

services:
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1G"
    # ports:
    #   - 4160:4160
    #   - 4161:4161
    networks:
      - net_def

  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1G"
    depends_on:
      - nsqlookupd
    # ports:
    #   - 4150:4150
    #   - 4151:4151
    networks:
      - net_def
    volumes:
      - data:/data
      - certs:/etc/ssl/certs

  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1G"
    depends_on:
      - nsqlookupd
    networks:
      - net_def
    # ports:
    #   - 4171:4171

volumes:
  data:
    name: nsqd_data
  certs:
    name: nsqd_certs