version: '3'

networks:
  net_def:
    external: true
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: 0 # IP 伪装, 为 0 无法访问容器网络之外的网络

services:
  nsqadmin:
    image: nsqio/nsq
    restart: unless-stopped
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1G"
    networks:
      - net_def
    # ports:
    #   - 4171:4171
